### ISSUE TITLE
Alternate trivia question types

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#157]
Currently, we have one type of trivia: a question, with three possible answers. 

We could add a few different types of trivia in addition to this - like showing a picture and asking "what is this thing," or playing an audio file.

### Questions we need from Story Team:

- [ ] Picture-type question
- [ ] Audio questions
- [ ] True/False question

### Tasks for Game Engine Team:

- [ ] Update the JSON question structure
- [ ] Create new UI for alternate question types
- [ ] Make new question types answerable
